Repository KBSC2/Soundify, pull requests merged in 2020-11, with the labels that each got.

#4 [BACK-17] Added controller for EF
  Controller/Controller.csproj
  Controller/DbController.cs
  Tests/Tests.csproj
  View/MainWindow.xaml.cs
  View/View.csproj
Labels: backend

#7 [Hotfix] Fixed imports in MainWindows.xaml.cs
  View/MainWindow.xaml.cs
Labels: frontend, hotfix

#3 Play song, info and slide bar
  Controller/Controller.csproj
  Controller/Data.cs
  Model/Model.csproj
  Model/Song.cs
  Tests/Tests.csproj
  View/DataContext.cs
  View/MainWindow.xaml
  View/MainWindow.xaml.cs
  View/View.csproj
Labels: frontend

#8 Back 7 24 playlist and song controller
  Controller/DbController.cs
  Controller/DbControllers/PlaylistController.cs
  Controller/DbControllers/PlaylistSongController.cs
  Controller/DbControllers/SongController.cs
  Model/DbModels/DbModel.cs
  Model/DbModels/PlaylistSong.cs
  Model/Program.cs
  View/MainWindow.xaml.cs
Labels: backend

#10 [PROJ-19] Nummer afspelen en cachen
  .github/workflows/dotnet-core.yml
  Controller/AudioPlayer.cs
  Controller/Controller.csproj
  Controller/FileCache.cs
  Controller/FileTransfer.cs
  Model/Model.csproj
  Model/Program.cs
  Model/SongAudioFile.cs
  Model/SongAudioFile.cs~HEAD
  Tests/Controller_AudioPlayerShould.cs
  Tests/Controller_FileCacheShould.cs
  Tests/Tests.csproj
  View/DataContext.cs
  View/MainWindow.xaml
  View/MainWindow.xaml.cs
  View/View.csproj
  View/dansenaandegracht.mp3
Labels: backend

#13 Back 11 delete song from playlist
  Controller/DbController.cs
  Controller/DbControllers/PlaylistSongController.cs
  Tests/Tests.csproj
Labels: backend

#16 SSH tunnel created in background
  View/MainWindow.xaml.cs
Labels: backend

#23 User controller added
  Controller/DbControllers/UserController.cs
  Controller/PasswordController.cs
  Model/Data/DatabaseContext.cs
  Model/DbModels/User.cs
  Model/Enums/RegistrationResults.cs
  Model/Migrations/DatabaseContextModelSnapshot.cs
  View/MainWindow.xaml.cs
Labels: backend

#26 Added unit tests for user registration
  Tests/Controller_UserController_UserSignup.cs
Labels: test

#29 Proj 4 revert
  Controller/DbControllers/PlaylistController.cs
  Controller/DbControllers/PlaylistSongController.cs
  Controller/DbControllers/SongController.cs
  Model/Contexts/PlaylistDataContext.cs
  Model/EventArgs/MenuItemRoutedEventArgs.cs
  Model/ListItems/SongInfo.cs
  Model/Model.csproj
  Tests/Controller_DbControllers_PlaylistSongControllerTest.cs
  Tests/ControllorDeactivate-DeletePlaylist.cs
  View/DataContexts/PlaylistDataContext.cs
  View/DataContexts/PlaylistMenuDataContext.cs
  View/ListItems/SongInfo.cs
  View/MainWindow.xaml.cs
  View/Screens/PlaylistMenuScreen.xaml
  View/Screens/PlaylistMenuScreen.xaml.cs
  View/Screens/PlaylistScreen.xaml
  View/Screens/PlaylistScreen.xaml.cs
Labels: backend, hotfix

#32 [PROJ-1] User login
  Controller/DbControllers/DbController.cs
  Controller/DbControllers/UserController.cs
  Model/Enums/LoginResults.cs
  Model/Enums/ScreenNames.cs
  Tests/Controller_UserController_UserLogin.cs
  Tests/Controller_UserController_UserSignup.cs
  View/DataContexts/DataContext.cs
  View/DataContexts/UserDataContext.cs
  View/LoginScreen.xaml
  View/LoginScreen.xaml.cs
  View/MainWindow.xaml
  View/MainWindow.xaml.cs
  View/RegisterScreen.xaml.cs
Labels: backend, frontend, test

#22 Added Searchengines to playlist & Songs
  Controller/DbControllers/PlaylistController.cs
  Controller/DbControllers/SongController.cs
  Tests/ControlersTests/SearchTests/Controller_Playlist_SearchOnString.cs
  Tests/ControlersTests/SearchTests/Controller_Song_SearchOnString.cs
Labels: backend

#41 [PROJ-25] Play song in playlist
  Controller/AudioPlayer.cs
  Controller/DbControllers/PlaylistSongController.cs
  Model/Data/DatabaseContext.cs
  Model/Migrations/20201118145922_UserTableAdded.cs
  Model/Migrations/20201119105447_UserTableUsernameAdded.cs
  Tests/Controller_AudioPlayerShould.cs
  Tests/Controller_DbControllers_PlaylistSongControllerTest.cs
  View/ChangePassword.xaml.cs
  View/DataContexts/DataContext.cs
  View/DataContexts/PlaylistDataContext.cs
  View/ListItems/SongInfo.cs
  View/LoginScreen.xaml.cs
  View/MainWindow.xaml
  View/MainWindow.xaml.cs
  View/Screens/PlaylistMenuScreen.xaml
  View/Screens/PlaylistMenuScreen.xaml.cs
  View/Screens/PlaylistScreen.xaml
  View/Screens/PlaylistScreen.xaml.cs
  View/Screens/SettingScreen.xaml.cs
Labels: backend, frontend

#43 personalized playlists, (user bound)
  Controller/DbControllers/PlaylistController.cs
  Tests/ControlersTests/SearchTests/Controller_Playlist_SearchOnString.cs
  Tests/Controller_PlaylistController_GetActivePlaylistsShould.cs
  View/DataContexts/PlaylistMenuDataContext.cs
  View/DataContexts/SearchDataContext.cs
  View/Screens/PlaylistMenuScreen.xaml.cs
Labels: backend

#44 [FEATURE] test database
  Model/Data/DatabaseContext.cs
  Model/Migrations/20201119105447_UserTableUsernameAdded.Designer.cs
  Model/Migrations/20201119105447_UserTableUsernameAdded.cs
  Tests/ControlersTests/SearchTests/Controller_Playlist_SearchOnString.cs
  Tests/ControlersTests/SearchTests/Controller_Song_SearchOnString.cs
  Tests/Controller_AudioPlayerShould.cs
  Tests/Controller_DbControllers_PlaylistSongControllerTest.cs
  Tests/Controller_PlaylistController_GetActivePlaylistsShould.cs
  Tests/Controller_UserController_UserLogin.cs
  Tests/Controller_UserController_UserSignup.cs
  Tests/ControllorDeactivate-DeletePlaylist.cs
Labels: hotfix

#45 Volume slider fix and minimum screensize
  View/MainWindow.xaml
Labels: frontend, hotfix

#50 Paul's first code cleanup
  Controller/DbControllers/UserController.cs
  Controller/PasswordController.cs
  Controller/SSHController.cs
  Model/ChangePasswordEventArgs.cs
  Model/EventArgs/MenuItemRoutedEventArgs.cs
  Tests/Controller_UserController_UserSignup.cs
  View/MainWindow.xaml.cs
Labels: backend

#51 [HOTFIX] remove credentials and make mock db for tests
  .gitignore
  Controller/AudioPlayer.cs
  Controller/DbControllers/DbController.cs
  Controller/DbControllers/PlaylistController.cs
  Controller/DbControllers/PlaylistSongController.cs
  Controller/DbControllers/SongController.cs
  Controller/DbControllers/UserController.cs
  Controller/PasswordController.cs
  Controller/SSHController.cs
  Model/Data/DatabaseContext.cs
  Model/Database/Contexts/DatabaseContext.cs
  Model/Database/Contexts/IDatabaseContext.cs
  Model/Database/Contexts/MockDatabaseContext.cs
  Model/DbModels/DbModel.cs
  Model/Migrations/20201112092348_Added_Song_Playlist.Designer.cs
  Model/Migrations/20201116090702_addedDatacolumsToPlaylist.Designer.cs
  Model/Migrations/20201116103210_changedSongColumnDurationToDouble.Designer.cs
  Model/Migrations/20201116123454_addArtistColumnToSong.Designer.cs
  Model/Migrations/20201117085501_Soundify.Designer.cs
  Model/Migrations/20201117103801_addedColumnsToPlaylist.Designer.cs
  Model/Migrations/20201118145922_UserTableAdded.Designer.cs
  Model/Migrations/20201118151905_PlaylistUserColumn.Designer.cs
  Model/Migrations/20201120063136_AddedIndexToPlaylistSongs.Designer.cs
  Model/Migrations/DatabaseContextModelSnapshot.cs
  Model/Model.csproj
  Tests/FileCache/Controller_FileCacheShould.cs
  Tests/Local/Controller_AudioPlayerShould.cs
  Tests/Local/Controller_SSHtunnel_DatabaseTest.cs
  Tests/Playlists/Controller_DbControllers_PlaylistSongControllerTest.cs
  Tests/Playlists/Controller_PlaylistController_GetActivePlaylistsShould.cs
  Tests/Playlists/ControllorDeactivate-DeletePlaylist.cs
  Tests/SearchTests/Controller_Playlist_SearchOnString.cs
  Tests/SearchTests/Controller_Song_SearchOnString.cs
  Tests/Users/Controller_UserController_UserLogin.cs
  Tests/Users/Controller_UserController_UserSignup.cs
  View/App.Config
  View/ChangePassword.xaml.cs
  View/Components/PasswordBoxMonitor.cs
  View/DataContexts/PlaylistDataContext.cs
  View/DataContexts/PlaylistMenuDataContext.cs
  View/DataContexts/SearchDataContext.cs
  View/ListItems/SongInfo.cs
  View/LoginScreen.xaml.cs
  View/MainWindow.xaml.cs
  View/RegisterScreen.xaml.cs
  View/Screens/PlaylistMenuScreen.xaml.cs
  View/Screens/PlaylistScreen.xaml.cs
  View/Screens/SearchScreen.xaml.cs
Labels: backend

#52 Fix local tests to use mock db
  Controller/AudioPlayer.cs
  Controller/DbControllers/PlaylistSongController.cs
  Controller/FileTransfer.cs
  Controller/SSHController.cs
  Tests/Local/Controller_AudioPlayerShould.cs
Labels: backend

#53 Re naming testen
  Tests/Local/Controller_AudioPlayer_Should.cs
  Tests/Local/Controller_FileCache_Should.cs
  Tests/Local/Controller_SSHtunnel_DatabaseTest.cs
  Tests/Playlists/Controller_PlaylistController_GetActivePlaylistsShould.cs
  Tests/Playlists/Controller_PlaylistControllor_DeactivateDeletePlaylist.cs
  Tests/Playlists/Controller_PlaylistSongController_AddDeleteFromPlaylistSong.cs
  Tests/SearchTests/Controller_PlaylistController_SearchOnString.cs
  Tests/SearchTests/Controller_SongController_SearchOnString.cs
  Tests/Users/Controller_UserController_UserSignup.cs
Labels: test

#55 Added enter to login, register, changepassword and recenter all windows
  View/ChangePassword.xaml
  View/ChangePassword.xaml.cs
  View/LoginScreen.xaml
  View/LoginScreen.xaml.cs
  View/MainWindow.xaml
  View/RegisterScreen.xaml
  View/RegisterScreen.xaml.cs
  View/Styles/Watermark.xaml
Labels: frontend

#59 Proj 35] email service
  Controller/EmailController.cs
  Model/MailTemplates/MailTemplate.cs
  Model/MailTemplates/MailVerificationTemplate.cs
Labels: backend

#63 Proj 32 email register verificatie
  Controller/DbControllers/UserController.cs
  Model/Enums/LoginResults.cs
  Model/MailTemplates/MailVerificationTemplate.cs
  Tests/Users/Controller_UserController_UserLogin.cs
  View/EmailVerificationScreen.xaml
  View/EmailVerificationScreen.xaml.cs
  View/LoginScreen.xaml.cs
  View/RegisterScreen.xaml.cs
Labels: backend

#64 screens fixed and sander's broken code, not broken anymore
  View/ChangePasswordScreen.xaml
  View/EmailVerificationScreen.xaml.cs
  View/ForgotPasswordScreen.xaml
  View/ForgotPasswordScreen.xaml.cs
  View/ForgotpasswordTokenSendScreen.xaml
  View/ForgotpasswordTokenSendScreen.xaml.cs
  View/LoginScreen.xaml
  View/LoginScreen.xaml.cs
  View/MainWindow.xaml
  View/MainWindow.xaml.cs
  View/RegisterScreen.xaml
  View/RegisterScreen.xaml.cs
Labels: bug
