Repository KBSC2/Soundify, pull requests merged in 2020-12, with the labels that each got.

#69 Proj 38 add song to queue
  Controller/AudioPlayer.cs
  Tests/Local/Controller_AudioPlayer_Should.cs
  View/DataContexts/DataContext.cs
  View/DataContexts/QueueDataContext.cs
  View/ListItems/SongInfo.cs
  View/MainWindow.xaml.cs
  View/Screens/PlaylistScreen.xaml
  View/Screens/PlaylistScreen.xaml.cs
  View/Screens/QueueScreen.xaml
  View/Screens/QueueScreen.xaml.cs
  View/Screens/SearchScreen.xaml
  View/Screens/SearchScreen.xaml.cs
  View/Screens/SettingScreen.xaml.cs
Labels: backend

#73 Fixes
  Controller/AudioPlayer.cs
  Controller/CoinsController.cs
  Controller/DbControllers/ArtistController.cs
  Controller/DbControllers/DbController.cs
  Controller/DbControllers/PlaylistController.cs
  Controller/DbControllers/PlaylistSongController.cs
  Controller/DbControllers/RolePermissionsController.cs
  Controller/DbControllers/SongController.cs
  Controller/DbControllers/UserController.cs
  Controller/EmailController.cs
  Controller/FileCache.cs
  Controller/FileTransfer.cs
  Controller/PasswordController.cs
  Controller/SSHController.cs
  Model/Database/Contexts/MockDatabaseContext.cs
  Model/DbModels/Artist.cs
  Model/Enums/Enumeration.cs
  Model/Enums/PasswordScore.cs
  Model/MailTemplates/MailSongApprovalTemplate.cs
  Tests/Local/Controller_AudioPlayer_Should.cs
  Tests/Playlists/Controller_PlaylistController_GetActivePlaylistsShould.cs
  Tests/Playlists/Controller_PlaylistControllor_DeactivateDeletePlaylist.cs
  Tests/Playlists/Controller_PlaylistSongController_AddDeleteFromPlaylistSong.cs
  Tests/SearchTests/Controller_PlaylistController_SearchOnString.cs
  Tests/SearchTests/Controller_SongController_SearchOnString.cs
  Tests/Users/Controller_UserController_RoleDesignation.cs
  Tests/Users/Controller_UserController_UserLogin.cs
  Tests/Users/Controller_UserController_UserSignup.cs
  View/ChangePasswordScreen.xaml.cs
  View/Components/ID3DurationPropertyConverter.cs
  View/Components/MenuButton.cs
  View/DataContexts/ArtistDataContext.cs
  View/EmailVerificationScreen.xaml.cs
  View/ForgotPasswordScreen.xaml.cs
  View/ForgotpasswordTokenSendScreen.xaml.cs
  View/LoginScreen.xaml
  View/LoginScreen.xaml.cs
  View/MainWindow.xaml
  View/MainWindow.xaml.cs
  View/RegisterScreen.xaml.cs
  View/RequestArtist.xaml.cs
  View/Screens/ArtistScreen.xaml.cs
  View/soundify.png
Labels: backend, hotfix

#75 tests added for acces
  Controller/DbControllers/SongController.cs
  Controller/FileCache.cs
  Controller/FileTransfer.cs
  Controller/SSHController.cs
  Model/Database/Contexts/MockDatabaseContext.cs
  Tests/Users/Controller_User_HasPermission.cs
  View/Screens/ArtistScreen.xaml.cs
Labels: test

#82 Tests controllers
  Controller/AudioPlayer.cs
  Controller/CoinsController.cs
  Controller/DbControllers/ArtistController.cs
  Controller/DbControllers/DbController.cs
  Controller/DbControllers/PermissionController.cs
  Controller/DbControllers/PlaylistController.cs
  Controller/DbControllers/PlaylistSongController.cs
  Controller/DbControllers/RequestController.cs
  Controller/DbControllers/RoleController.cs
  Controller/DbControllers/RolePermissionsController.cs
  Controller/DbControllers/SongController.cs
  Controller/DbControllers/UserController.cs
  Controller/EmailController.cs
  Controller/FileCache.cs
  Controller/FileTransfer.cs
  Controller/PasswordController.cs
Labels: documentation

#84 update buttons fixed
  View/Components/MenuButton.cs
  View/Components/PermissionButton.cs
  View/LoginScreen.xaml.cs
  View/MainWindow.xaml
  View/MainWindow.xaml.cs
  View/PopUpNoRights.xaml.cs
Labels: backend

#83 FIX Testreport errors, added a test for currentuser
  Controller/DbControllers/UserController.cs
  Model/Enums/RegistrationResults.cs
  Tests/Users/Controller_UserController_UserLogin.cs
  Tests/Users/Controller_UserController_UserSignup.cs
  View/ChangePasswordScreen.xaml.cs
  View/ForgotPasswordScreen.xaml.cs
  View/LoginScreen.xaml.cs
  View/RegisterScreen.xaml.cs
  View/Screens/SettingScreen.xaml.cs
  View/View.csproj
Labels: backend

#90 Right click songinfoscreen
  Controller/AudioPlayer.cs
  Model/Enums/ScreenNames.cs
  Model/EventArgs/MenuItemRoutedEventArgs.cs
  View/App.xaml
  View/Components/BooleanToVisibilityConverter.cs
  View/DataContexts/ArtistDataContext.cs
  View/DataContexts/PlaylistDataContext.cs
  View/DataContexts/SearchDataContext.cs
  View/DataContexts/SongListDataContext.cs
  View/ListItems/SongInfo.cs
  View/MainWindow.xaml.cs
  View/Screens/AdminScreen.xaml.cs
  View/Screens/ArtistScreen.xaml
  View/Screens/PlaylistMenuScreen.xaml.cs
  View/Screens/PlaylistScreen.xaml
  View/Screens/PlaylistScreen.xaml.cs
  View/Screens/SearchScreen.xaml
  View/Screens/SearchScreen.xaml.cs
  View/Screens/SettingScreen.xaml.cs
  View/Styles/SongList.xaml
  View/Styles/SongList.xaml.cs
Labels: backend

#91 Song info in bottom main window
  Controller/AudioPlayer.cs
  View/Assets/NoImage.png
  View/Assets/null.png
  View/DataContexts/DataContext.cs
  View/DataContexts/SongInfoDataContext.cs
  View/MainWindow.xaml
  View/Screens/ArtistScreen.xaml.cs
  View/View.csproj
Labels: bug

#93 Added Song list
  Model/Enums/ScreenNames.cs
  View/App.xaml
  View/Components/GridViewBehaviours.cs
  View/DataContexts/DataContext.cs
  View/DataContexts/SongListDataContext.cs
  View/ListItems/SongInfo.cs
  View/MainWindow.xaml
  View/MainWindow.xaml.cs
  View/Screens/PlaylistScreen.xaml.cs
  View/Screens/QueueScreen.xaml
  View/Screens/SongListScreen.xaml
  View/Screens/SongListScreen.xaml.cs
  View/Styles/SongList.xaml
  View/Styles/SongList.xaml.cs
Labels: frontend

#97 Test mainwindow
  Controller/AudioPlayer.cs
  Controller/DbControllers/RequestController.cs
  Controller/QueueController.cs
  Tests/Local/Controller_AudioPlayer_Should.cs
  Tests/Local/Controller_FileCache_Should.cs
  Tests/Local/Controller_QueueController_Should.cs
  View/DataContexts/AdminDataContext.cs
  View/DataContexts/DataContext.cs
  View/DataContexts/PlaylistDataContext.cs
  View/DataContexts/QueueDataContext.cs
  View/DataContexts/RequestDataContext.cs
  View/DataContexts/SongListDataContext.cs
  View/ListItems/SongRequestInfo.cs
  View/MainWindow.xaml
  View/MainWindow.xaml.cs
  View/RequestArtist.xaml.cs
  View/Screens/ArtistScreen.xaml.cs
  View/Screens/PlaylistScreen.xaml.cs
  View/Screens/QueueScreen.xaml.cs
  View/SongInfoScreen.xaml.cs
Labels: backend, test

#104 Proj 49 account alteration
  Controller/DbControllers/UserController.cs
  Model/Enums/NewUserInfo.cs
  Tests/Local/Controller_AudioPlayer_Should.cs
  Tests/Local/Controller_QueueController_Should.cs
  Tests/Playlists/Controller_PlaylistSongController_AddDeleteFromPlaylistSong.cs
  Tests/Requests/Controller_RequestController_AddRequest.cs
  Tests/Requests/View_RequestScreen_Approve_Button_Click.cs
  Tests/Requests/View_RequestScreen_Decline_Button_Click.cs
  Tests/SearchTests/Controller_SongController_SearchOnString.cs
  Tests/Users/Controller_UserController_ChangeDetails.cs
  Tests/Users/Controller_UserController_RoleDesignation.cs
  Tests/Users/Controller_UserController_UserLogin.cs
  Tests/Users/Controller_UserController_UserSignup.cs
  Tests/Users/Controller_User_HasPermission.cs
  View/NewUserInformationScreen.xaml
  View/NewUserInformationScreen.xaml.cs
  View/Screens/AdminScreen.xaml
  View/Screens/AlbumUploadScreen.xaml
  View/Screens/ArtistScreen.xaml
  View/Screens/HomeScreen.xaml
  View/Screens/PlaylistMenuScreen.xaml
  View/Screens/RequestScreen.xaml
  View/Screens/SearchScreen.xaml
  View/Screens/SettingScreen.xaml
  View/Screens/SettingScreen.xaml.cs
  View/Screens/ShopScreen.xaml
  View/Screens/SongAlterationScreen.xaml
  View/Screens/SongListScreen.xaml
Labels: backend, frontend, test

#102 Bug standard font family
  Controller/DbControllers/ArtistController.cs
  Controller/DbControllers/UserController.cs
  Model/Enums/ScreenNames.cs
  Tests/Users/Controller_UserController_RoleDesignation.cs
  View/App.xaml
  View/ChangePasswordScreen.xaml.cs
  View/Components/RoleIDConverter.cs
  View/DataContexts/RoleAssignmentDataContext.cs
  View/EmailVerificationScreen.xaml.cs
  View/ForgotPasswordScreen.xaml.cs
  View/ForgotpasswordTokenSendScreen.xaml.cs
  View/LoginScreen.xaml.cs
  View/MainWindow.xaml.cs
  View/PopUpNoRights.xaml.cs
  View/RegisterScreen.xaml.cs
  View/RequestArtist.xaml.cs
  View/Screens/AdminScreen.xaml
  View/Screens/AdminScreen.xaml.cs
  View/Screens/RoleAssignmentScreen.xaml
  View/Screens/RoleAssignmentScreen.xaml.cs
  View/SongInfoScreen.xaml.cs
  View/Styles/Watermark.xaml
Labels: backend, bug, frontend, test

#107 Fix SearchFunction Currentuser
  View/Screens/RoleAssignmentScreen.xaml.cs
Labels: bug

#109 Fixed tracking issue
  Controller/DbControllers/DbController.cs
Labels: hotfix

#106 Proj 51 rechten rollen
  Controller/DbControllers/PlaylistSongController.cs
  Controller/DbControllers/RequestController.cs
  Controller/DbControllers/RolePermissionsController.cs
  Model/DbModels/RolePermissions.cs
  Model/Enums/ScreenNames.cs
  View/App.xaml
  View/DataContexts/PermissionAssignmentDataContext.cs
  View/Screens/AdminScreen.xaml
  View/Screens/AdminScreen.xaml.cs
  View/Screens/PermissionAssignmentScreen.xaml
  View/Screens/PermissionAssignmentScreen.xaml.cs
  View/Screens/PlaylistMenuScreen.xaml.cs
  View/Screens/ShopScreen.xaml.cs
Labels: backend

#110 Mainwindow-white-fixed
  View/LoginScreen.xaml.cs
  View/MainWindow.xaml.cs
Labels: frontend

#111 New assets 2
  Controller/AudioPlayer.cs
  Controller/CoinsController.cs
  Controller/DbControllers/DbController.cs
  Controller/DbControllers/PlaylistSongController.cs
  Model/SongAudioFile.cs
  View/App.xaml
  View/Assets/Coins.png
  View/Assets/SoundMuted.png
  View/Assets/down.png
  View/Assets/exit.png
  View/Assets/minimize.png
  View/Assets/pause.png
  View/Assets/playplaylist.png
  View/Assets/slider.png
  View/Assets/up.png
  View/ChangePasswordScreen.xaml
  View/ChangePasswordScreen.xaml.cs
  View/Components/MenuButton.cs
  View/DataContexts/ArtistDataContext.cs
  View/DataContexts/DataContext.cs
  View/DataContexts/SongListDataContext.cs
  View/EmailVerificationScreen.xaml
  View/EmailVerificationScreen.xaml.cs
  View/ForgotPasswordScreen.xaml
  View/ForgotPasswordScreen.xaml.cs
  View/ForgotpasswordTokenSendScreen.xaml
  View/ForgotpasswordTokenSendScreen.xaml.cs
  View/LoginScreen.xaml
  View/LoginScreen.xaml.cs
  View/MainWindow.xaml
  View/MainWindow.xaml.cs
  View/PopUpNoRights.xaml
  View/RegisterScreen.xaml
  View/RegisterScreen.xaml.cs
  View/RequestArtist.xaml
  View/RequestArtist.xaml.cs
  View/Screens/PlaylistMenuScreen.xaml
  View/Screens/PlaylistScreen.xaml
  View/Screens/PlaylistScreen.xaml.cs
  View/Screens/QueueScreen.xaml
  View/Screens/RequestScreen.xaml
  View/Screens/SettingScreen.xaml
  View/Screens/SettingScreen.xaml.cs
  View/SongInfoScreen.xaml
  View/Styles/SongList.xaml
  View/Styles/SongList.xaml.cs
  View/Styles/Watermark.xaml
  View/View.csproj
Labels: frontend

#112 fixes refreshing of requests and uploading in artistscreen
  View/Screens/ArtistScreen.xaml.cs
  View/Screens/RequestScreen.xaml.cs
Labels: frontend

#114 small change
  View/Assets/soundifyMedium.png
  View/NewUserInformationScreen.xaml
  View/Screens/ShopScreen.xaml.cs
Labels: hotfix

#113 Todo's fix ben, code optimalization
  Controller/AudioPlayer.cs
  View/MainWindow.xaml.cs
  View/Screens/AlbumUploadScreen.xaml.cs
  View/Screens/PlaylistMenuScreen.xaml.cs
  View/Screens/QueueScreen.xaml.cs
  View/Screens/RequestScreen.xaml.cs
  View/Screens/RoleAssignmentScreen.xaml.cs
  View/Screens/SearchScreen.xaml.cs
  View/Screens/SettingScreen.xaml.cs
  View/Screens/ShopScreen.xaml.cs
  View/Styles/SongList.xaml.cs
Labels: backend, documentation

#119 queue fix and design
  Controller/AudioPlayer.cs
  Tests/Local/Controller_AudioPlayer_Should.cs
  Tests/Local/Controller_QueueController_Should.cs
  Tests/Playlists/Controller_PlaylistControllor_DeactivateDeletePlaylist.cs
  View/DataContexts/DataContext.cs
  View/ListItems/SongInfo.cs
  View/MainWindow.xaml
  View/MainWindow.xaml.cs
  View/Screens/AdminScreen.xaml
  View/Screens/ArtistScreen.xaml
  View/Screens/QueueScreen.xaml
  View/Screens/QueueScreen.xaml.cs
  View/Screens/RequestScreen.xaml
  View/Screens/RoleAssignmentScreen.xaml
  View/Screens/SongListScreen.xaml
  View/Styles/SongList.xaml
Labels: bug, frontend
